config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kind.rb
# frozen_string_literal: true

class Kind < ApplicationRecord
  has_many :contacts
end

app/controllers/kinds_controller.rb
# frozen_string_literal: true

class KindsController < ApplicationController
  before_action :set_kind, only: %i[show edit update destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show; end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit; end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_kind
    @kind = Kind.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kind_params
    params.require(:kind).permit(:description)
  end
end

app/helpers/kinds_helper.rb
# frozen_string_literal: true

module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true, html: { class: "basic-grey" }) do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Tipos</h1>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, placeholder: "Descrição" %>
  </div>

  <div class="actions">
    <%= form.submit t('buttons.submit'), class: "button"  %>
    <%= link_to t('buttons.back'), kinds_path, class: "button" %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/index.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<h1><%= @kinds.model.model_name.human(count: @kinds.count)%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('message.description')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr style= "background: <%= cycle("#e1e6ef", "white")%>">
        <td><%= link_to kind.description, kind %></td>
        <td><%= link_to t('buttons.edit'), edit_kind_path(kind) %></td>
        <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: t('message.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_kind_path %>
</div>

app/views/kinds/new.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/show.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('message.description') %>:</strong>
  <%= @kind.description %>
</p>

<%= link_to t('buttons.edit'), edit_kind_path(@kind) %>
|
<%= link_to t('buttons.back'), kinds_path %>
</div>