config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone.rb
# frozen_string_literal: true

class Phone < ApplicationRecord
  belongs_to :contact
end

app/controllers/phones_controller.rb
# frozen_string_literal: true

class PhonesController < ApplicationController
  before_action :set_phone, only: %i[show edit update destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.order(:phone).page(params[:page]).per(15)
  end

  # GET /phones/1
  # GET /phones/1.json
  def show; end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit; end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_phone
    @phone = Phone.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def phone_params
    params.require(:phone).permit(:phone, :contact_id)
  end
end

app/helpers/phones_helper.rb
# frozen_string_literal: true

module PhonesHelper
end

app/views/phones/_form.html.erb
<%= form_with(model: phone, local: true, html: { class: "basic-grey" }) do |form| %>
<% if phone.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(phone.errors.count, "error") %>
      prohibited this phone from being saved:</h2>

    <ul>
      <% phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Telefones</h1>

<div class="field">
  <%= form.label :phone %>
  <%= form.text_field :phone, placeholder: "Ex.: 85 999-999-999" %>
</div>

<div class="field">
  <%= form.label :contact_id %>
  <%= form.text_field :contact_id, placeholder: "Digite um Nome para o Contato" %>
</div>

<div class="actions">
  <%= form.submit t('buttons.submit'), class: "button" %>
  <%= link_to t('buttons.back'), phones_path, class: "button" %>
</div>
<% end %>

app/views/phones/edit.html.erb
<%= render 'form', phone: @phone %>

app/views/phones/index.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<h1><%= t('message.phone')%></h1>

<table>
  <thead>
    <tr>
      <th><%= @phones.model.human_attribute_name("phone")%></th>
      <th><%= @phones.model.human_attribute_name("contact")%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= link_to phone.phone, phone %></td>
        <td><%= phone.contact.name %></td>

        <td><%= link_to t('buttons.edit'), edit_phone_path(phone) %></td>
        <td><%= link_to t('buttons.destroy'), phone, method: :delete, data: { confirm: t('message.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_phone_path %>
<%= paginate @phones, window: 2, left: 1, right: 1 %>
</div>

app/views/phones/new.html.erb
<%= render 'form', phone: @phone %>

app/views/phones/show.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('message.phone') %>:</strong>
  <%= @phone.phone %>
</p>

<p>
  <strong><%= t('message.contact') %>:</strong>
  <%= @phone.contact.name %>
</p>

<%= link_to t('buttons.edit'), edit_phone_path(@phone) %>
|
<%= link_to t('buttons.back'), phones_path %>
</div>