config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :kind
  has_one :address, dependent: :destroy
  has_many :phones

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(30)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
    option_for_select
  end

  # GET /contacts/1/edit
  def edit
    option_for_select
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def option_for_select
    @kind_option_for_select = Kind.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :email, :kind_id, :rmk, address_attributes: %i[street city state],
                                                                   phones_attributes: %i[id phone _destroy])
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true, html: { class: "basic-grey" }) do |form| %>
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(contact.errors.count, "error") %>
      prohibited this contact from being saved:</h2>

    <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Contatos</h1>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, placeholder: "Seu Nome Completo" %>
</div>

<div class="field">
  <%= form.label :email %>
  <%= form.text_field :email, placeholder: "Digite um E-mail Válido" %>
</div>

<div class="field">
  <%= form.label :kind_id %>
  <%= collection_select(:contact, :kind_id, @kind_option_for_select, :id, :description) %>
</div>

<%= form.fields_for :address do |address_fields| %>
<div class="field">
  <%= form.label :street %>
  <%= address_fields.text_field :street %>
</div>
<div class="field">
  <%= form.label :city %>
  <%= address_fields.text_field :city %>
</div>
<div class="field">
  <%= address_fields.label :state %>
  <%= address_fields.select :state, options_for_states(@contact.address.state) %>
</div>
<% end %>
<div id="phones">
<%= form.fields_for :phones do |phones_fields| %>
<%= render partial: "phone_fields", locals: { f: phones_fields } %>
<% end %>
<div class="field">
<%= form.label :phones, ">" %><br>
<%= link_to_add_association('Adicionar Telefone', form, :phones, class: "button" )%><br>
</div>
</div>
<br><br>
<div class="field">
<%= form.label :rmk %>
<%= form.text_area :rmk, placeholder: "Comente Aqui." %>
</div>

<div class="actions">
<%= form.submit t('buttons.submit'), class: "button" %>
<%= link_to t('buttons.back'), contacts_path, class: "button" %>
</div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.text_field :phone, class: "phone-field" %>
    <%= f.label :phone %>
    <%=  link_to_remove_association 'remover', f, class: "button"  %>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<div class="basic-grey">
  <p id="notice"><%= notice %></p>

  <h1><%= "#{t('message.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}"%></h1>

  <table>
    <thead>
      <tr>
        <th><%= @contacts.model.human_attribute_name("name")%></th>
        <th><%= @contacts.model.human_attribute_name("kind")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr style= "background: <%= cycle("#e1e6ef", "white")%>">
          <td><%= link_to contact.name, contact %></td>
          <td><%= contact.kind.description %></td>
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('message.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to t('buttons.new'), new_contact_path%>
  <%= paginate @contacts, window: 2, left: 1, right: 1 %>
</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<div class="basic-grey">

<p id="notice"><%= notice %></p>
<h1>
  <%= @contact.name %>
</h1>

<p>
  <strong><%= t('message.email') %>:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong><%=t('message.kind')%>:</strong>
  <%= @contact.kind.description %>
</p>

<p>
  <strong><%= t('message.rmk') %>:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to t('buttons.edit'), edit_contact_path(@contact) %>
|
<%= link_to t('buttons.back'), contacts_path %>
</div>