config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

class AddressesController < ApplicationController
  before_action :set_address, only: %i[show edit update destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.order(:state).page(params[:page]).per(15)
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show; end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit; end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def address_params
    params.require(:address).permit(:street, :city, :state, :contact_id)
  end
end

app/helpers/addresses_helper.rb
# frozen_string_literal: true

module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true, html: { class: "basic-grey" }) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Endereço</h1>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, placeholder: "Rua Humberto Martins de Castro, 370" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, placeholder: "Caucaia" %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, options_for_states(@address.state) %>
  </div>

  <div class="field">
    <%= form.label :contact_id %>
    <%= form.text_field :contact_id, placeholder: "Contato" %>
  </div>

  <div class="actions">
    <%= form.submit t('buttons.submit'), class: "button" %>
    <%= link_to t('buttons.back'), addresses_path, class: "button" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<%= render 'form', address: @address %>

app/views/addresses/index.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<h1><%= @addresses.model.model_name.human(count: @addresses.count)%></h1>

<table>
  <thead>
    <tr>
      <th><%= @addresses.model.human_attribute_name("contact")%></th>
      <th><%= @addresses.model.human_attribute_name("street")%></th>
      <th><%= @addresses.model.human_attribute_name("city")%></th>
      <th><%= @addresses.model.human_attribute_name("state")%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= link_to address.contact.name, address %></td>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= link_to t('buttons.edit'), edit_address_path(address) %></td>
        <td><%= link_to t('buttons.destroy'), address, method: :delete, data: { confirm: t('message.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_address_path %>
<%= paginate @addresses, window: 2, left: 1, right: 1 %>
</div>

app/views/addresses/new.html.erb
<%= render 'form', address: @address %>

app/views/addresses/show.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('message.street')%>:</strong>
  <%= @address.street %>
</p>

<p>
  <strong><%= t('message.city')%>:</strong>
  <%= @address.city %>
</p>

<p>
  <strong><%= t('message.state')%>:</strong>
  <%= @address.state %>
</p>

<p>
  <strong><%= t('message.contact')%>:</strong>
  <%= @address.contact.name %>
</p>

<%= link_to t('buttons.edit'), edit_address_path(@address) %> |
<%= link_to t('buttons.back'), addresses_path %>
</div>